export const API_BASE_HEADER = {
	"accept": "application/json",
	"content-type": "application/json",
};

// dispatchers

export const INTERNAL_DISPATCH = "INTERNAL_DISPATCH";

export const API_OPEN_GET_SYSTEMINFOS = "API_OPEN_GET_SYSTEMINFOS";
export const API_MERCHANT_GET_LEAD = "API_MERCHANT_GET_LEAD";

export const API_MERCHANT_LIST_CURRENCIES_DISPATCH = "API_MERCHANT_LIST_CURRENCIES_DISPATCH";
export const API_MERCHANT_LIST_DEAL_DISPATCH = "API_MERCHANT_LIST_DEAL_DISPATCH";
export const API_MERCHANT_VIEW_DEAL_DISPATCH = "API_MERCHANT_VIEW_DEAL_DISPATCH";
export const API_MERCHANT_LIST_OFFER_DISPATCH = "API_MERCHANT_LIST_OFFER_DISPATCH";
export const API_MERCHANT_LIST_TASK_DISPATCH = "API_MERCHANT_LIST_TASK_DISPATCH";
export const API_MERCHANT_LIST_COUPON_DISPATCH = "API_MERCHANT_LIST_COUPON_DISPATCH";
export const API_MERCHANT_UPDATE_COUPON_DISPATCH = "API_MERCHANT_UPDATE_COUPON_DISPATCH";
export const API_MERCHANT_VIEW_COUPON_DISPATCH= "API_MERCHANT_VIEW_COUPON_DISPATCH";
export const API_MERCHANT_VIEW_WALLET_DISPATCH = "API_MERCHANT_VIEW_WALLET_DISPATCH";
export const API_MERCHANT_LIST_WALLETTRANSACTION_DISPATCH = "API_MERCHANT_LIST_WALLETTRANSACTION_DISPATCH";
export const API_MERCHANT_LIST_TASKACTIVITY_DISPATCH = "API_MERCHANT_LIST_TASKACTIVITY_DISPATCH";
export const API_MERCHANT_VIEW_TASK_DISPATCH = "API_MERCHANT_VIEW_TASK_DISPATCH";
export const API_MERCHANT_VIEW_SURPRISE_DISPATCH = "API_MERCHANT_VIEW_SURPRISE_DISPATCH";
export const API_MERCHANT_LIST_NOTIFICATION_DISPATCH = "API_MERCHANT_LIST_NOTIFICATION_DISPATCH";
export const API_MERCHANT_LIST_SURPRISEACTIVITY_DISPATCH = "API_MERCHANT_LIST_SURPRISEACTIVITY_DISPATCH";
export const API_MERCHANT_LIST_SURPRISE_DISPATCH = "API_MERCHANT_LIST_SURPRISE_DISPATCH";

export const API_SUCCESS_DISPATCH = "API_SUCCESS_DISPATCH";
export const API_IGNORE_DISPATCH = "API_IGNORE_DISPATCH";
export const API_ERROR_DISPATCH = "API_ERROR_DISPATCH";



