export const API_BASE_HEADER = {
	"accept": "application/json",
	"content-type": "application/json",
};

// dispatchers

export const INTERNAL_DISPATCH = "INTERNAL_DISPATCH";

export const API_MERCHANT_GET_AGGREEGATEDDETAILS = "API_MERCHANT_GET_AGGREEGATEDDETAILS";
export const API_MERCHANT_GET_ENTITY = "API_MERCHANT_GET_ENTITY";
export const API_MERCHANT_GET_LEAD = "API_MERCHANT_GET_LEAD";

export const API_MERCHANT_LIST_DEAL_DISPATCH = "API_MERCHANT_LIST_DEAL_DISPATCH";
export const API_MERCHANT_VIEW_DEAL_DISPATCH = "API_MERCHANT_VIEW_DEAL_DISPATCH";

export const API_MERCHANT_LIST_DISCOUNT_DISPATCH = "API_MERCHANT_LIST_DISCOUNT_DISPATCH";
export const API_MERCHANT_VIEW_DISCOUNT_DISPATCH = "API_MERCHANT_VIEW_DISCOUNT_DISPATCH";

export const API_MERCHANT_LIST_COUPON_DISPATCH = "API_MERCHANT_LIST_COUPON_DISPATCH";
export const API_MERCHANT_UPDATE_COUPON_DISPATCH = "API_MERCHANT_UPDATE_COUPON_DISPATCH";
export const API_MERCHANT_UPDATE_METADETAIL_DISPATCH = "API_MERCHANT_UPDATE_METADETAIL_DISPATCH";
export const API_MERCHANT_UPDATE_LEAD_DISPATCH = "API_MERCHANT_UPDATE_LEAD_DISPATCH";
export const API_MERCHANT_VIEW_COUPON_DISPATCH = "API_MERCHANT_VIEW_COUPON_DISPATCH";
export const API_MERCHANT_VIEW_WALLET_DISPATCH = "API_MERCHANT_VIEW_WALLET_DISPATCH";
export const API_MERCHANT_LIST_WALLETTRANSACTION_DISPATCH = "API_MERCHANT_LIST_WALLETTRANSACTION_DISPATCH";
export const API_MERCHANT_LIST_REVIEW_DISPATCH = "API_MERCHANT_LIST_REVIEW_DISPATCH";
export const API_MERCHANT_VIEW_REVIEW_DISPATCH = "API_MERCHANT_VIEW_REVIEW_DISPATCH";


export const API_MERCHANT_LIST_NOTIFICATION_DISPATCH = "API_MERCHANT_LIST_NOTIFICATION_DISPATCH";

export const API_MERCHANT_LIST_INSTRUCTION_DISPATCH = "API_MERCHANT_LIST_INSTRUCTION_DISPATCH";

export const API_SUCCESS_DISPATCH = "API_SUCCESS_DISPATCH";
export const API_IGNORE_DISPATCH = "API_IGNORE_DISPATCH";
export const API_ERROR_DISPATCH = "API_ERROR_DISPATCH";



